name: Provision  nginx
on:
  workflow_dispatch:
    inputs:
      tfname:
        description: Clustername
        required: true
        default: 'tfcluster1'
        type: string
jobs:
  provision-nginx:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::658643245563:role/gh-role
          aws-region: us-east-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: install aws cli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
      - name: Terraform Apply
        id:   apply
        env:
          TF_VAR_tfname:  "${{ github.event.inputs.tfname }}"
        run: |
          aws eks update-kubeconfig --name "${{ github.event.inputs.tfname }}"-eks-cluster --region us-east-1
          cd nginx
          terraform init
          terraform validate
          terraform plan 
          terraform apply -auto-approve
